services:
  - type: worker
    name: narion-render-autonom
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 trigger_watcher_sms.py"
    envVars:
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM_NUMBER
        sync: false
      - key: TWILIO_TO_NUMBER
        sync: false
